name: Check

on:
  workflow_dispatch:
    inputs:
      ticket:
        type: string
        description: ⚠️CAREFUL!⚠️ Show me your ticket starting with 'CR-'! If you want to skip it, type 'skip'.
        required: true

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print ticket number
      run: echo ${{ inputs.ticket }}
      
    - name: Is ticket OK?
      if: ${{ !startsWith(inputs.ticket, 'CR-')  }} || ${{ !contains(inputs.ticket, 'skip') }}
      run: |
        echo "Given ticket number is not valid and you didn't wanted to skip that."
        exit 1
    
    - name: If ticket OK
      run: echo "Everything is OK then!"
