name: Check

on:
  workflow_dispatch:
    inputs:
      ticket:
        type: string
        description: ⚠️ Show me your ticket! ⚠️
        required: true

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print ticket number
      run: echo ${{ inputs.ticket }}
      
    - name: Check the ticket
      if: ${{ !startsWith(inputs.ticket, "CR-") }}
      run: exit 1
