name: Check

on:
  workflow_dispatch:
    inputs:
      ticket:
        type: string
        description: ⚠️ Show me your ticket! ⚠️
        required: true

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print ticket number
      run: echo ${{ inputs.ticket }}
      
    - name: Is ticket OK?
      if: ${{ !startsWith(inputs.ticket, 'CR-') }}
      run: |
        echo "Given ticket number is not valid. Has to start with 'CR-'"
        exit 1
