name: Check

on:
  workflow_dispatch:
    inputs:
      ticket:
        type: string
        description: ⚠️ Fill in your `ticket` starting with 'CR-' or skip it by 'skip'.
        required: true

jobs:
  my-job:
    env:
      USER-INPUT: ${{ inputs.ticket }}
    runs-on: ubuntu-latest
    steps:
    - name: Print ticket answer
      run: echo ${{ env.USER-INPUT }}
      
    - name: Is valid ticket
      run: echo ${{ startsWith(env.USER-INPUT, 'CR-') }}
      
    - name: Should skip
      run: echo ${{ contains(env.USER-INPUT, 'skip') }}
      
    - name: Is ticket OK?
      if: ${{ (!startsWith(env.USER-INPUT, 'CR-') && !contains(env.USER-INPUT, 'skip')) }}
      run: |
        echo "Given ticket number is not valid and you didn't wanted to skip that."
        exit 1
    
    - name: If ticket OK
      run: echo "Everything is OK then!"
