name: Continue

on:
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Infinite job
      run: echo -e "\nfrom time import sleep\ni=0\nwhile True:\n\ti + 1\n\tsleep(1)" | python 
