name: Continue

on:
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: |
        while :
        do
          echo "Press [CTRL+C] to stop.."
          sleep 1
        done
