name: Setup Infrastructure

on:
  workflow_dispatch:

env:
  TF_VERSION: 1.4.6
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  setup-infrastructure:
    name: Setup Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Get the code (Checkout)
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Setup Working directory
        id: workdir-setup
        run: echo "working_directory=./terraform/_prep/infrastructure" >> "$GITHUB_OUTPUT"

      - name: Run Terraform
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve
        working-directory: ${{steps.workdir-setup.outputs.working_directory}}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: infrastructure_ids
          path: "./terraform/_prep/infrastructure/infrastructure_ids.txt"
